### ISSUE TITLE
Seek usage help

### ISSUE THREAD

**Issue by Sibyl1122** [kubevela/workflow#119]
hello, I recently learn "kubevela/workflow", your work is so great.
But there are some nuts when I use the builtin function "#ApplyInParallel"
Function:  Input a volume name list,  and I want to add snapshot on these volumes by **adding a field in "spec".**【this operator has been defined】

This is the cue template code:
```
import (
	"vela/op"
	"encoding/json"
)

"add-warpdrive-snapshot": {
	alias: ""
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	output: {
		 data:  op.#Steps & {
		   	  wvs: [ for idx,wv in parameter.warpdrive_list {
		   	  	 op.#Read & {
		   	  	 	value : {
						kind: "WarpdriveVolume"
    						apiVersion: "tos.trans.io/v1"
     					 	metadata: name: wv
     					 }
							}
		   	 	 }]  @step(1)

		   	  log10086: op.#Log & { data: wvs[0] }  @step(2)

          patches: [  for v in wvs {
          	    op.#PatchK8sObject & {
                                value: v.value
                                patch: {
                                	// +patchStrategy=retainKeys
                                	spec: snapshots: ["flowsnapshot"]
                                }
												 }
                } ] @step(3)

        objects: [ for patchResult in patches {patchResult.result}]  @step(4)


        log10087: op.#Log & {
        	data: json.Marshal(patches[0])
        }  @step(5)

        apply: op.#ApplyInParallel & {
		value: objects
						} @step(6)

        }

	}
	parameter: {
		warpdrive_list: [string]
	}
}
```

The result was that **there was no error reported and the "WorkflowRun" run successfully.** But there were also **no logs reported** which I have configured in the code. And t**he filed was not be added** as expectation. So the operation "patch and apply" were failed.

Did I misunderstand the usage of #Steps or other builtin function ？ pls help me

**Comment by Sibyl1122** [comment]
Reason ：
<img width="691" alt="image" src="https://user-images.githubusercontent.com/50979245/212810644-507b5d59-af65-40d8-93cb-a17849f00aa0.png">

**Comment by FogDong** [comment]
Yes, you need to use `op.#Steps` if you want to use a set of operations, refer to: https://kubevela.io/docs/platform-engineers/workflow/cue-actions#steps

Actually, there's no need to add `@step(num)` behind every field, workflow will execute your cue fields sequentially.
