### ISSUE TITLE
执行apply-app报错

### ISSUE THREAD

**Issue by pbxie** [kubevela/workflow#169]
我在工作流中添加一个apply-app的节点，内容如下：
![image](https://github.com/kubevela/workflow/assets/37398509/9fd3b5fe-4784-4bf0-90ac-7f9f1fb2708e)

执行时报错：
![image](https://github.com/kubevela/workflow/assets/37398509/71d7d16e-c77b-4d60-a598-b5d4dc45efff)

**Comment by anoop2811** [comment]
This should already be fixed in the v0.6.0 of vela workflow. Can you try updating the version of the addon? This is caused due to some breaking change in the upstream k8s api header changes which have been updated in 0.6.0 of workflow
